services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env.docker
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres
    env_file: ./.env.docker
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U productuser -d productdb"]
      interval: 10s
      retries: 10
      start_period: 60s
    

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A instaapp worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A instaapp beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
