# Generated by Django 5.1.7 on 2025-03-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_story_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='likes',
        ),
    ]
