# Generated by Django 5.1.7 on 2025-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
        ('posts', '0007_remove_story_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_hashtag', to='hashtags.hashtag'),
        ),
    ]
