# Generated by Django 5.1.7 on 2025-03-28 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 28, 7, 2, 57, 413376, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
