# Generated by Django 5.1.7 on 2025-03-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
