# Generated by Django 5.1.7 on 2025-03-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('posts', '0001_initial'),
        ('profiles', '0002_alter_profile_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.post'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
    ]
