# Generated by Django 5.1.7 on 2025-03-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_unique_together_alter_like_post_and_more'),
        ('posts', '0003_alter_post_image_alter_post_video'),
        ('profiles', '0003_alter_profile_profile_picture_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('profile', 'post')},
        ),
    ]
