# Generated by Django 5.1.7 on 2025-03-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_alter_like_unique_together_like_comment_and_more'),
        ('posts', '0005_story_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to='posts.story'),
        ),
    ]
